### ISSUE TITLE
How to get logs for a branch and all of its nested branches?

### ISSUE THREAD

**Issue by ysmaoui** [gdemengin/pipeline-logparser#17]
Hi,

so if I understood correctly a branch in the LogParser library can be a one of parallel branches in a Jenkins pipeline, it can be also a stage in one parallel branch of the pipeline, this is a bit confusing from the point of view of a jenkins pipeline

but anyway, the main use case that I have is to get the logs of a single jenkins-pipeline-parallel-block-branch, in version 2.0.1 I used to provide the name of that pipeline branch in the filter to get everything ( all the stages of that pipeline-branch as well )

With 3.1.2 it seems that the stages are considered nested branches, and their logs are filtered out.

so my questions is how to get the logs of a jenkins-pipeline-branch ( in parallel block ) with all the stages ( the nested branches ).
How should the filter look like? 

Thanks

**Comment by gdemengin** [comment]
- you can use option showStages=false and stages will not be considered as parallel branches
```
@Library('pipeline-logparser@main') _

parallel (
  branch1: { 
      echo 'in branch1'
  },
  branch2: { 
      echo 'in branch2'
      stage('stageA') {
          echo 'in branch2.stageA'
      }
  },
)

print logparser.getLogsWithBranchInfo(showStages: false, filter: [ 'branch2' ])
```
result:
```
[branch2] in branch2
[branch2] in branch2.stageA
```

- or you can filter the stages like this
```
@Library('pipeline-logparser@main') _

parallel (
  branch1: { 
      echo 'in branch1'
  },
  branch2: { 
      echo 'in branch2'
      stage('stageA') {
          echo 'in branch2.stageA'
      }
  },
)

print logparser.getLogsWithBranchInfo(filter: [ 'branch2', [ 'branch2', '.*' ] ])
```
result:
```
[branch2] in branch2
[branch2] [stageA] in branch2.stageA
```
the second filter `[ 'branch2', '.*' ]` will catch any nested branches or stages inside branch 'branch2'
(and it keeps the stage name as prefix of the logs which can be useful information)

agreed mixing stages and branches is confusing, but it can be useful to get logs from a specific stage and the stage name that's why option showStages was defaulted to true in version 3.

does it answer the question ?

**Comment by ysmaoui** [comment]
great 
thanks @gdemengin 

both methods worked like a charm ;)
