### ISSUE TITLE
Add an option to allow writing logs directly to a file instead of writing to the heap

### ISSUE THREAD

**Issue by ysmaoui** [gdemengin/pipeline-logparser#19]
a Place holder ticket for the PR 
https://github.com/gdemengin/pipeline-logparser/pull/18

provides the possibilitiy to write the logs directly to a file in the workspace
improves performance
reduces Heap consumption with big logs

the new options are:
writeToFile (boolean) - defaults to false
filePath: a FilePath object to the log file - FilePath to allow writing to file on Jenkins agent workspace

opens an outputStream to the file in FilePath and writes directly in there

**Comment by ysmaoui** [comment]
getting a FilePath object to a file on agent workspace: ( value for filePath ) :
this requires some script approvals ( or wrappers in a global shared library ) 

```
new FilePath(Jenkins.getInstance().getComputer(steps.env['NODE_NAME']).getChannel(), steps.pwd()).child(relativePathToFileInWorkspace)
```

**Comment by gdemengin** [comment]
actually wouldn't `new FilePath(new File(pathToFile))` do the same ? (path to a file in the local workspace)
but it still requires some approvals

edit: no it does not do the same: it will create a file on the master node regardless of the current node

**Comment by gdemengin** [comment]
I propose to close this one with https://github.com/gdemengin/pipeline-logparser/pull/21 which adds 2 functions
- `void writeLogsWithBranchInfo(hudson.FilePath filePath, java.util.LinkedHashMap options = [:], build = currentBuild)`
to write the logs directly in the filePath object
- `void writeLogsWithBranchInfo(String node, String path, java.util.LinkedHashMap options = [:], build = currentBuild)`
to create the hudson.FilePath from node and Path first (and avoid requiring script approvals)

as discussed here https://github.com/gdemengin/pipeline-logparser/pull/18#issuecomment-1173173730 I think it makes more sense to add these new functions rather than new options to preserve the original purpose of getLogswithBranchInfo (which is to get logs in a String buffer)

**Comment by gdemengin** [comment]
writeLogsWithBranchInfo added in 3.2
